Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,27 +13,31 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          submodules: true
+    - name: Checkout repository
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+        submodules: true
 
-      - name: Set up Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: '3.22.0'
+    - name: Set up Flutter
+      uses: subosito/flutter-action@v2
+      with:
+        flutter-version: '3.22.0'
 
-      - name: Navigate to project directory
-        run: |
-          cd galaktika_sklad_ready  # Переходим в директорию с проектом
-          pwd                       # Проверяем текущую директорию
-          ls -la                    # Смотрим содержимое
+    - name: Navigate to project directory
+      run: |
+        cd galaktika_sklad_ready
+        pwd
+        ls -la
 
-      - name: Verify Flutter installation
-        run: flutter doctor
+    - name: Verify Flutter installation
+      run: flutter doctor
 
-      - name: Check pubspec.yaml existence
-        run: |
-          if ! [ -f "pubspec.yaml" ]; then
-            echo
+    - name: Check pubspec.yaml existence
+      run: |
+        if [ ! -f "pubspec.yaml" ]; then
+          echo "pubspec.yaml not found!"
+          exit 1
+        fi
+
+    - name:
